# Generated by Django 4.2.7 on 2024-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_spam_user_password_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spam',
            name='id',
        ),
        migrations.AddField(
            model_name='spam',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spam',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
